name: "Elixir Checks"
description: "Run typical checks"
# branding:
#   icon: "check-square"
#   color: "green"
inputs:
  base-dir:
    description: "Mix app directory"
    required: true
    default: "./"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # runs:
    #   using: "composite"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3
      # - uses: sevenshores/action-elixir-checks@v0.1.2-alpha

      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.

      - name: Install dependencies
        working-directory: ${{ inputs.base-dir }}
        run: mix deps.get
        shell: bash

      - name: Check formatting
        working-directory: ${{ inputs.base-dir }}
        run: mix format --check-formatted
        shell: bash

      - name: Run tests
        working-directory: ${{ inputs.base-dir }}
        run: mix test
        shell: bash
# runs:
#   using: "composite"
#   steps:
#     - name: Install dependencies
#       working-directory: ${{ inputs.base-dir }}
#       run: mix deps.get
#       shell: bash

#     - name: Check formatting
#       working-directory: ${{ inputs.base-dir }}
#       run: mix format --check-formatted
#       shell: bash

# - name: Compile dependencies
#   working-directory: ${{ inputs.base-dir }}
#   run: mix deps.compile
#   shell: bash

# - name: Compile app
#   working-directory: ${{ inputs.base-dir }}
#   run: mix compile
#   shell: bash

# - name: Compile app for test
#   working-directory: ${{ inputs.base-dir }}
#   run: mix compile
#   shell: bash
#   env:
#     MIX_ENV: test

# - name: Run Credo
#   working-directory: ${{ inputs.base-dir }}
#   run: mix credo
#   shell: bash

# - name: Run Dialyzer
#   working-directory: ${{ inputs.base-dir }}
#   run: mix dialyzer
#   shell: bash
