name: tool_box Continuous Integration

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - feat-automations

jobs:
  Test:
    services:
      db:
        image: postgres:14
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    strategy:
      matrix:
        elixir: ["1.13.4"]
        otp: [25]
    env:
      MIX_ENV: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test

  Format:
    strategy:
      matrix:
        elixir: ["1.13.4"]
        otp: [25]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix format --check-formatted

  Credo:
    strategy:
      matrix:
        elixir: ["1.13.4"]
        otp: [25]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix credo

  Dialyzer:
    strategy:
      matrix:
        elixir: ["1.13.4"]
        otp: [25]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set cache key
        id: cache_key
        run: |
          mix_hash="${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}"
          echo "::set-output name=mix_hash::$mix_hash"
      - uses: actions/cache@v3
        with:
          path: |
            _build/dev/*.plt
            _build/dev/*.plt.hash
          key: plt-cache-${{ steps.cache_key.outputs.mix_hash }}
          restore-keys: |
            plt-cache-
      - uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix dialyzer
